### ISSUE TITLE
TODO tasks

### ISSUE THREAD

**Issue by sundy-li** [sundy-li/pa#1]
-  [x] Support optional metadata support  + schema  (thrift)   -> doki23
-  [x] List Array/Struct Array (repeat level / define level)  -->kikkon
-  [x] Support read from a single pa file   (fetch schema and detect the offset as parquet) -> doki23 
-  [xxxx] Refer IPC  (align 64 byte) --> kikkon 
-  [x] 1 + 4 + 4  (compression method + compressed_size + uncompressed_size)  -> doki23 
-  [x] Fix bugs (boolean Array)  -->kikkon 
-  [ ] tests  (random array ), Performance  (all)
-  [x] Databend Native Engine  @sundy-li  

-  [xxxx] Skip pages seek trait  (
select * from hits where URL like '%google%'; {   [.. {.x.x.} ..]  })
-  [xxxx] Databend protocol (flight)
